/** @format */

// lib\5e-data.ts

export const SCHOOLS = [
    "Abjuration",
    "Conjuration",
    "Divination",
    "Enchantment",
    "Evocation",
    "Illusion",
    "Necromancy",
    "Transmutation",
];

export const CLASSES = [
    "Artificer",
    "Bard",
    "Cleric",
    "Druid",
    "Paladin",
    "Ranger",
    "Sorcerer",
    "Warlock",
    "Wizard",
];

export const STARTING_SPELLS = {
    Artificer: 3,
    Bard: 6,
    Cleric: 7,
    Druid: 6,
    Paladin: 2,
    Ranger: 2,
    Sorcerer: 6,
    Warlock: 4,
    Wizard: 7,
};

export const SPELLS_PER_LEVEL = {
    Artificer: {
        // cantrips from table, prepared spells = Intelligence modifier + half artificer level rounded down
        "1": { cantrips: 2, spells: null, maxSpellLevel: 1 },
        "2": { cantrips: 2, spells: null, maxSpellLevel: 1 },
        "3": { cantrips: 2, spells: null, maxSpellLevel: 1 },
        "4": { cantrips: 2, spells: null, maxSpellLevel: 1 },
        "5": { cantrips: 2, spells: null, maxSpellLevel: 2 },
        "6": { cantrips: 2, spells: null, maxSpellLevel: 2 },
        "7": { cantrips: 2, spells: null, maxSpellLevel: 2 },
        "8": { cantrips: 2, spells: null, maxSpellLevel: 2 },
        "9": { cantrips: 2, spells: null, maxSpellLevel: 3 },
        "10": { cantrips: 3, spells: null, maxSpellLevel: 3 },
        "11": { cantrips: 3, spells: null, maxSpellLevel: 3 },
        "12": { cantrips: 3, spells: null, maxSpellLevel: 3 },
        "13": { cantrips: 3, spells: null, maxSpellLevel: 4 },
        "14": { cantrips: 3, spells: null, maxSpellLevel: 4 },
        "15": { cantrips: 3, spells: null, maxSpellLevel: 4 },
        "16": { cantrips: 3, spells: null, maxSpellLevel: 4 },
        "17": { cantrips: 4, spells: null, maxSpellLevel: 5 },
        "18": { cantrips: 5, spells: null, maxSpellLevel: 5 },
        "19": { cantrips: 5, spells: null, maxSpellLevel: 5 },
        "20": { cantrips: 5, spells: null, maxSpellLevel: 5 },
    },

    Bard: {
        "1": { cantrips: 2, spells: 4, maxSpellLevel: 1 },
        "2": { cantrips: 2, spells: 5, maxSpellLevel: 1 },
        "3": { cantrips: 2, spells: 6, maxSpellLevel: 2 },
        "4": { cantrips: 3, spells: 7, maxSpellLevel: 2 },
        "5": { cantrips: 3, spells: 9, maxSpellLevel: 3 },
        "6": { cantrips: 3, spells: 10, maxSpellLevel: 3 },
        "7": { cantrips: 3, spells: 11, maxSpellLevel: 4 },
        "8": { cantrips: 3, spells: 12, maxSpellLevel: 4 },
        "9": { cantrips: 3, spells: 14, maxSpellLevel: 5 },
        "10": { cantrips: 4, spells: 15, maxSpellLevel: 5 },
        "11": { cantrips: 4, spells: 16, maxSpellLevel: 6 },
        "12": { cantrips: 4, spells: 16, maxSpellLevel: 6 },
        "13": { cantrips: 4, spells: 17, maxSpellLevel: 7 },
        "14": { cantrips: 4, spells: 17, maxSpellLevel: 7 },
        "15": { cantrips: 4, spells: 18, maxSpellLevel: 8 },
        "16": { cantrips: 4, spells: 18, maxSpellLevel: 8 },
        "17": { cantrips: 4, spells: 19, maxSpellLevel: 9 },
        "18": { cantrips: 4, spells: 20, maxSpellLevel: 9 },
        "19": { cantrips: 4, spells: 21, maxSpellLevel: 9 },
        "20": { cantrips: 4, spells: 22, maxSpellLevel: 9 },
    },

    Cleric: {
        "1": { cantrips: 3, spells: 4, maxSpellLevel: 1 },
        "2": { cantrips: 3, spells: 5, maxSpellLevel: 1 },
        "3": { cantrips: 3, spells: 6, maxSpellLevel: 2 },
        "4": { cantrips: 4, spells: 7, maxSpellLevel: 2 },
        "5": { cantrips: 4, spells: 9, maxSpellLevel: 3 },
        "6": { cantrips: 4, spells: 10, maxSpellLevel: 3 },
        "7": { cantrips: 4, spells: 11, maxSpellLevel: 4 },
        "8": { cantrips: 4, spells: 12, maxSpellLevel: 4 },
        "9": { cantrips: 4, spells: 14, maxSpellLevel: 5 },
        "10": { cantrips: 5, spells: 15, maxSpellLevel: 5 },
        "11": { cantrips: 5, spells: 16, maxSpellLevel: 6 },
        "12": { cantrips: 5, spells: 16, maxSpellLevel: 6 },
        "13": { cantrips: 5, spells: 17, maxSpellLevel: 7 },
        "14": { cantrips: 5, spells: 17, maxSpellLevel: 7 },
        "15": { cantrips: 5, spells: 18, maxSpellLevel: 8 },
        "16": { cantrips: 5, spells: 18, maxSpellLevel: 8 },
        "17": { cantrips: 5, spells: 19, maxSpellLevel: 9 },
        "18": { cantrips: 5, spells: 20, maxSpellLevel: 9 },
        "19": { cantrips: 5, spells: 21, maxSpellLevel: 9 },
        "20": { cantrips: 5, spells: 22, maxSpellLevel: 9 },
    },

    Druid: {
        "1": { cantrips: 2, spells: 4, maxSpellLevel: 1 },
        "2": { cantrips: 2, spells: 5, maxSpellLevel: 1 },
        "3": { cantrips: 2, spells: 6, maxSpellLevel: 2 },
        "4": { cantrips: 3, spells: 7, maxSpellLevel: 2 },
        "5": { cantrips: 3, spells: 9, maxSpellLevel: 3 },
        "6": { cantrips: 3, spells: 10, maxSpellLevel: 3 },
        "7": { cantrips: 3, spells: 11, maxSpellLevel: 4 },
        "8": { cantrips: 3, spells: 12, maxSpellLevel: 4 },
        "9": { cantrips: 3, spells: 14, maxSpellLevel: 5 },
        "10": { cantrips: 4, spells: 15, maxSpellLevel: 5 },
        "11": { cantrips: 4, spells: 16, maxSpellLevel: 6 },
        "12": { cantrips: 4, spells: 16, maxSpellLevel: 6 },
        "13": { cantrips: 4, spells: 17, maxSpellLevel: 7 },
        "14": { cantrips: 4, spells: 17, maxSpellLevel: 7 },
        "15": { cantrips: 4, spells: 18, maxSpellLevel: 8 },
        "16": { cantrips: 4, spells: 18, maxSpellLevel: 8 },
        "17": { cantrips: 4, spells: 19, maxSpellLevel: 9 },
        "18": { cantrips: 4, spells: 20, maxSpellLevel: 9 },
        "19": { cantrips: 4, spells: 21, maxSpellLevel: 9 },
        "20": { cantrips: 4, spells: 22, maxSpellLevel: 9 },
    },

    Paladin: {
        "1": { cantrips: 0, spells: 2, maxSpellLevel: 1 },
        "2": { cantrips: 0, spells: 3, maxSpellLevel: 1 },
        "3": { cantrips: 0, spells: 4, maxSpellLevel: 1 },
        "4": { cantrips: 0, spells: 5, maxSpellLevel: 1 },
        "5": { cantrips: 0, spells: 6, maxSpellLevel: 2 },
        "6": { cantrips: 0, spells: 6, maxSpellLevel: 2 },
        "7": { cantrips: 0, spells: 7, maxSpellLevel: 2 },
        "8": { cantrips: 0, spells: 7, maxSpellLevel: 2 },
        "9": { cantrips: 0, spells: 9, maxSpellLevel: 3 },
        "10": { cantrips: 0, spells: 9, maxSpellLevel: 3 },
        "11": { cantrips: 0, spells: 10, maxSpellLevel: 3 },
        "12": { cantrips: 0, spells: 10, maxSpellLevel: 3 },
        "13": { cantrips: 0, spells: 11, maxSpellLevel: 4 },
        "14": { cantrips: 0, spells: 11, maxSpellLevel: 4 },
        "15": { cantrips: 0, spells: 12, maxSpellLevel: 4 },
        "16": { cantrips: 0, spells: 12, maxSpellLevel: 4 },
        "17": { cantrips: 0, spells: 14, maxSpellLevel: 5 },
        "18": { cantrips: 0, spells: 14, maxSpellLevel: 5 },
        "19": { cantrips: 0, spells: 15, maxSpellLevel: 5 },
        "20": { cantrips: 0, spells: 15, maxSpellLevel: 5 },
    },

    Ranger: {
        "1": { cantrips: 0, spells: 2, maxSpellLevel: 1 },
        "2": { cantrips: 0, spells: 3, maxSpellLevel: 1 },
        "3": { cantrips: 0, spells: 4, maxSpellLevel: 1 },
        "4": { cantrips: 0, spells: 5, maxSpellLevel: 1 },
        "5": { cantrips: 0, spells: 6, maxSpellLevel: 2 },
        "6": { cantrips: 0, spells: 6, maxSpellLevel: 2 },
        "7": { cantrips: 0, spells: 7, maxSpellLevel: 2 },
        "8": { cantrips: 0, spells: 7, maxSpellLevel: 2 },
        "9": { cantrips: 0, spells: 9, maxSpellLevel: 3 },
        "10": { cantrips: 0, spells: 9, maxSpellLevel: 3 },
        "11": { cantrips: 0, spells: 10, maxSpellLevel: 3 },
        "12": { cantrips: 0, spells: 10, maxSpellLevel: 3 },
        "13": { cantrips: 0, spells: 11, maxSpellLevel: 4 },
        "14": { cantrips: 0, spells: 11, maxSpellLevel: 4 },
        "15": { cantrips: 0, spells: 12, maxSpellLevel: 4 },
        "16": { cantrips: 0, spells: 12, maxSpellLevel: 4 },
        "17": { cantrips: 0, spells: 14, maxSpellLevel: 5 },
        "18": { cantrips: 0, spells: 14, maxSpellLevel: 5 },
        "19": { cantrips: 0, spells: 15, maxSpellLevel: 5 },
        "20": { cantrips: 0, spells: 15, maxSpellLevel: 5 },
    },

    Sorcerer: {
        "1": { cantrips: 4, spells: 2, maxSpellLevel: 1 },
        "2": { cantrips: 4, spells: 4, maxSpellLevel: 1 },
        "3": { cantrips: 4, spells: 6, maxSpellLevel: 2 },
        "4": { cantrips: 5, spells: 7, maxSpellLevel: 2 },
        "5": { cantrips: 5, spells: 9, maxSpellLevel: 3 },
        "6": { cantrips: 5, spells: 10, maxSpellLevel: 3 },
        "7": { cantrips: 5, spells: 11, maxSpellLevel: 4 },
        "8": { cantrips: 5, spells: 12, maxSpellLevel: 4 },
        "9": { cantrips: 5, spells: 14, maxSpellLevel: 5 },
        "10": { cantrips: 6, spells: 15, maxSpellLevel: 5 },
        "11": { cantrips: 6, spells: 16, maxSpellLevel: 6 },
        "12": { cantrips: 6, spells: 16, maxSpellLevel: 6 },
        "13": { cantrips: 6, spells: 17, maxSpellLevel: 7 },
        "14": { cantrips: 6, spells: 17, maxSpellLevel: 7 },
        "15": { cantrips: 6, spells: 18, maxSpellLevel: 8 },
        "16": { cantrips: 6, spells: 18, maxSpellLevel: 8 },
        "17": { cantrips: 6, spells: 19, maxSpellLevel: 9 },
        "18": { cantrips: 6, spells: 20, maxSpellLevel: 9 },
        "19": { cantrips: 6, spells: 21, maxSpellLevel: 9 },
        "20": { cantrips: 6, spells: 22, maxSpellLevel: 9 },
    },

    Warlock: {
        "1": { cantrips: 2, spells: 2, maxSpellLevel: 1 },
        "2": { cantrips: 2, spells: 3, maxSpellLevel: 1 },
        "3": { cantrips: 2, spells: 4, maxSpellLevel: 2 },
        "4": { cantrips: 3, spells: 5, maxSpellLevel: 2 },
        "5": { cantrips: 3, spells: 6, maxSpellLevel: 3 },
        "6": { cantrips: 3, spells: 7, maxSpellLevel: 3 },
        "7": { cantrips: 3, spells: 8, maxSpellLevel: 4 },
        "8": { cantrips: 3, spells: 9, maxSpellLevel: 4 },
        "9": { cantrips: 3, spells: 10, maxSpellLevel: 5 },
        "10": { cantrips: 4, spells: 10, maxSpellLevel: 5 },
        "11": { cantrips: 4, spells: 11, maxSpellLevel: 5 },
        "12": { cantrips: 4, spells: 11, maxSpellLevel: 5 },
        "13": { cantrips: 4, spells: 12, maxSpellLevel: 5 },
        "14": { cantrips: 4, spells: 12, maxSpellLevel: 5 },
        "15": { cantrips: 4, spells: 13, maxSpellLevel: 5 },
        "16": { cantrips: 4, spells: 13, maxSpellLevel: 5 },
        "17": { cantrips: 4, spells: 14, maxSpellLevel: 5 },
        "18": { cantrips: 4, spells: 14, maxSpellLevel: 5 },
        "19": { cantrips: 4, spells: 15, maxSpellLevel: 5 },
        "20": { cantrips: 4, spells: 15, maxSpellLevel: 5 },
    },

    Wizard: {
        "1": { cantrips: 3, spells: 4, maxSpellLevel: 1 },
        "2": { cantrips: 3, spells: 5, maxSpellLevel: 1 },
        "3": { cantrips: 3, spells: 6, maxSpellLevel: 2 },
        "4": { cantrips: 4, spells: 7, maxSpellLevel: 2 },
        "5": { cantrips: 4, spells: 9, maxSpellLevel: 3 },
        "6": { cantrips: 4, spells: 10, maxSpellLevel: 3 },
        "7": { cantrips: 4, spells: 11, maxSpellLevel: 4 },
        "8": { cantrips: 4, spells: 12, maxSpellLevel: 4 },
        "9": { cantrips: 4, spells: 14, maxSpellLevel: 5 },
        "10": { cantrips: 5, spells: 15, maxSpellLevel: 5 },
        "11": { cantrips: 5, spells: 16, maxSpellLevel: 6 },
        "12": { cantrips: 5, spells: 16, maxSpellLevel: 6 },
        "13": { cantrips: 5, spells: 17, maxSpellLevel: 7 },
        "14": { cantrips: 5, spells: 18, maxSpellLevel: 7 },
        "15": { cantrips: 5, spells: 19, maxSpellLevel: 8 },
        "16": { cantrips: 5, spells: 21, maxSpellLevel: 8 },
        "17": { cantrips: 5, spells: 22, maxSpellLevel: 9 },
        "18": { cantrips: 5, spells: 23, maxSpellLevel: 9 },
        "19": { cantrips: 5, spells: 24, maxSpellLevel: 9 },
        "20": { cantrips: 5, spells: 25, maxSpellLevel: 9 },
    },
};

export const MIN_LEVEL = 1;
export const MAX_LEVEL = 20;
